spring:
  application:
    name: schoolBack
  profiles:
    active: dev
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
  liquibase:
    change-log: classpath:db/changelog/changelog_master.yml

server:
  port: 8080

logging:
  level:
    com.school: DEBUG
    org.springframework.security: INFO
    liquibase: INFO

app:
  jwt-secret: YOUR_SUPER_SECRET_KEY_HERE_CHANGE_IT
  jwt-expiration-millis: 86400000 #24h