# Common

spring:
  application:
    name: schoolBack
  profiles:
    active: DEV
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
  liquibase:
    change-log: classpath:db/changelog/changelog.yml

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  level:
    root: INFO
    com.gmail.llemaxiss.app: INFO

app:
  version: 1.2.0
  jwt-secret: YOUR_SUPER_SECRET_KEY_HERE_CHANGE_IT
  jwt-expiration-millis: 86400000 #24h

# DEV profile
---
spring:
  config:
    activate:
      on-profile: DEV
  datasource:
    url: jdbc:postgresql://localhost:5432/school_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

logging:
  level:
    com.gmail.llemaxiss.app: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    liquibase: INFO

# PROD profile
---
spring:
  config:
    activate:
      on-profile: PROD
  datasource:
    url: jdbc:postgresql://localhost:5432/school_prod
    username: postgres
    password: postgres

logging:
  level:
    root: WARN
    com.gmail.llemaxiss.app: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    liquibase: WARN